# Description:
# Benchmarks for batching tree RNNs.

py_binary(
    name = "bench",
    srcs = ["bench.py"],
    srcs_version = "PY2AND3",
    deps = [
        "//tensorflow_fold/public:loom",
        "@org_tensorflow//tensorflow:tensorflow_py",
    ],
)
