# TensorFlow Fold.

licenses(["notice"])  # Apache 2.0

# This is needed for open-source Fold installation.
filegroup(
    name = "headers",
    srcs = glob(["**/*.h"]),
    visibility = ["//tensorflow_fold:__subpackages__"],
)
